#!/usr/bin/env sh

NET_BASE=/home/cqiu/deepLearningData/DeephiAlexNet
#/home/cqiu/eclipse_workspace/caffe-master-ristretto/build/tools/caffe test \
./build/tools/caffe test \
    --model=$NET_BASE/deephi_alexnet_int8_test.prototxt \
	--weights=$NET_BASE/decompressedAlexNet.caffemodel \
	--iterations=1

