#!/usr/bin/env sh

NET_BASE=/home/cqiu/deepLearningData/ResNetData/ResNet152Data
#/home/cqiu/eclipse_workspace/caffe-master-ristretto/build/tools/caffe test \
./build/tools/caffe test \
    --model=$NET_BASE/ResNet152Test.prototxt \
	--weights=$NET_BASE/ResNet-152-model.caffemodel \
	--iterations=20

